# Generated by Django 5.0.4 on 2024-06-25 01:56

import django_resized.forms
import users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["top", "left"],
                force_format="JPEG",
                keep_meta=True,
                quality=80,
                scale=0.5,
                size=[300, 300],
                upload_to=users.models.file_upload,
            ),
        ),
    ]
