# Generated by Django 5.0.4 on 2024-06-25 12:43

import django_resized.forms
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'left'], force_format=None, keep_meta=True, quality=80, scale=1, size=[300, 300], upload_to=users.models.file_upload),
        ),
    ]
