# Generated by Django 5.0.4 on 2024-07-08 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_customuser_email_en_customuser_email_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email_en",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_ru",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_uz",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username_en",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username_ru",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username_uz",
        ),
    ]
