# Generated by Django 5.0.4 on 2024-07-08 11:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.AlterModelOptions(
            name="clap",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Clap",
                "verbose_name_plural": "Claps",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["question"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
            },
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Follow",
                "verbose_name_plural": "Follows",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="pin",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Pin",
                "verbose_name_plural": "Pins",
            },
        ),
        migrations.AlterModelOptions(
            name="readinghistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Reading History",
                "verbose_name_plural": "Reading Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="recommendation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
            },
        ),
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["name"],
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
        migrations.AlterModelOptions(
            name="topicfollow",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Topic Follow",
                "verbose_name_plural": "Topic Follows",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
