# Generated by Django 5.0.4 on 2024-07-08 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_options_alter_clap_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="article",
            table="article",
        ),
        migrations.AlterModelTable(
            name="clap",
            table="clap",
        ),
        migrations.AlterModelTable(
            name="comment",
            table="comment",
        ),
        migrations.AlterModelTable(
            name="faq",
            table="faq",
        ),
        migrations.AlterModelTable(
            name="favorite",
            table="favorite",
        ),
        migrations.AlterModelTable(
            name="follow",
            table="follow",
        ),
        migrations.AlterModelTable(
            name="notification",
            table="notification",
        ),
        migrations.AlterModelTable(
            name="pin",
            table="pin",
        ),
        migrations.AlterModelTable(
            name="readinghistory",
            table="reading_history",
        ),
        migrations.AlterModelTable(
            name="recommendation",
            table="recommendation",
        ),
        migrations.AlterModelTable(
            name="report",
            table="report",
        ),
        migrations.AlterModelTable(
            name="topic",
            table="topic",
        ),
        migrations.AlterModelTable(
            name="topicfollow",
            table="topic_follow",
        ),
    ]
