# Generated by Django 5.0.4 on 2024-07-08 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "articles",
            "0004_remove_article_user_article_author_topic_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="clap",
            name="count",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
    ]
