# Generated by Django 5.0.4 on 2024-07-10 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_alter_topicfollow_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="topicfollow",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="topicfollow",
            constraint=models.UniqueConstraint(
                fields=("user", "topic"), name="unique_user_topic"
            ),
        ),
    ]
