# Generated by Django 5.0.4 on 2024-07-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0009_alter_topicfollow_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="reads_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
