# Generated by Django 5.0.4 on 2024-07-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0011_remove_recommendation_less_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="less",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_active": True},
                related_name="less_recommended",
                to="articles.topic",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="more",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_active": True},
                related_name="more_recommended",
                to="articles.topic",
            ),
        ),
    ]
